// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Phone     string           `json:"phone"`
	OwnerID   pgtype.Int4      `json:"owner_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
