// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (name, phone)
VALUES ($1, $2)
RETURNING id, name, phone, owner_id, created_at
`

type CreateContactParams struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact, arg.Name, arg.Phone)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE id = $1
`

func (q *Queries) DeleteContact(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteContact, id)
	return err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, name, phone, owner_id, created_at
FROM contacts
WHERE id = $1
`

func (q *Queries) GetContactByID(ctx context.Context, id int32) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getContacts = `-- name: GetContacts :many
SELECT id, name, phone, owner_id, created_at
FROM contacts c
ORDER BY c.name ASC
`

func (q *Queries) GetContacts(ctx context.Context) ([]Contact, error) {
	rows, err := q.db.Query(ctx, getContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET name = $2,
    phone = $3
WHERE id = $1
RETURNING id, name, phone, owner_id, created_at
`

type UpdateContactParams struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact, arg.ID, arg.Name, arg.Phone)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}
