// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	DeleteContact(ctx context.Context, id int32) error
	GetContactByID(ctx context.Context, id int32) (Contact, error)
	GetContacts(ctx context.Context) ([]Contact, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
}

var _ Querier = (*Queries)(nil)
